@WikiGuesser.Server_HostAddress = http://localhost:5084

GET {{WikiGuesser.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WikiGuesser.Server_HostAddress}}/api/wikipedia/GetRandomArticle

###

GET {{WikiGuesser.Server_HostAddress}}/api/wikipedia/article/Leuven

###

GET {{WikiGuesser.Server_HostAddress}}/api/wikipedia/cities

###


GET {{WikiGuesser.Server_HostAddress}}/api/wikipedia/location/Paris

###
